### ISSUE TITLE
How would the ProductsPagingSourceByCoroutine looks like for normal api call that doesn't support paging 

### ISSUE THREAD

**Issue by rawan-riwal** [Drjacky/MVVMTemplate#16]

**Comment by Drjacky** [comment]
You don't need that then.
Instead of injecting `ProductsPagingSourceByCoroutine ` in `RepositoryModule `, inject what we have in `ProductsPagingSourceByCoroutine` as the parameter (which is `ProductsApi `).

**Comment by rawan-riwal** [comment]
can you please follow up with me in your example , so this is how it would look like 

`class ProductsListRepositoryImpl @Inject constructor(
    private val productsApi: ProductsApi
) : ProductsListRepository {
  override fun getBeersListByCoroutine(ids: String): Flow<PagingData<Beer>> =
       productsApi.getBeersListByCoroutine(position)
                .map {
                    BeerMapper().mapLeftToRight(it)
                }
        }`
        
 Doing that will cause the following error 
`Suspend function 'getCountriesList' should be called only from a coroutine or another suspend function`

can you please help me to fix that so I can move forward. I don't want to just do what android studio suggest without understanding.

**Comment by Drjacky** [comment]
That means you need a coroutine builder:
```kotlin
X.launch {
HERE
```

Which `X` could be `lifecycleScope,  lifecycle.coroutineScope, viewLifecycleOwner.lifecycleScope` for Activity/Fragment, `viewModelScope` for ViewModel, ...; Which are tied up with their lifecycles.
