### ISSUE TITLE
What is the best way to implement a use case that doesn't have any params?

### ISSUE THREAD

**Issue by rawan-riwal** [Drjacky/MVVMTemplate#17]
Do I need to create a separate base use case that doesn't expect params to be passed, or just pass Void as param? what would be your way to handle that ?

**Comment by Drjacky** [comment]
You could have use cases without the parent class(that doesn't have the param), like this:
```kotlin
class MyUseCase @Inject constructor(
    private val myRepo: MyRepo,
) {

    operator fun invoke(): Flowable<MyModel> =
        myRepo.getAllOfThem()

}
```

But in point of my view,
- To have a concise code
- Following the same pattern you follow for the other use cases that accept params

It is better to have a parent class for these kinds of use cases as well:
```kotlin
interface ParentUseCase<Type : Any> {

    operator fun invoke(params: Params): Single<Type>

}
```
and the usage:
```kotlin
class MyUseCase @Inject constructor(
    private val myRepo: MyRepo,
) : ParentUseCase<Flowable<MyModel> {

    override fun invoke(): Flowable<MyModel> =
        myRepo.getAllOfThem()

}
```

______

You could pass Nothing as well to avoid making the code complex and having too much abstraction in your code. If you have lots of abstraction classes, go this way.
A good code is
+ Not a few abstractions
+ Not too many abstractions
+ Reuse what you have as much as you can until you realized you're mixing different logic (if-else)
