### ISSUE TITLE
[BUG]: Title goes here

### ISSUE THREAD

**Issue by mobilekosmos** [Drjacky/MVVMTemplate#20]
I don't understand why you have all those folders domain, presentation etc outside the app module, is this project supposed to be opened with Android Studio and work? Because it's not a typical Android project, I'm not being able to simply open it and run it.

**Comment by Drjacky** [comment]
Yes, those are modules. https://medium.com/proandroiddev/mvvm-with-clean-architecture-c2c021e05c89  

What version of AS are you using?
