### ISSUE TITLE
[BUG]: Title goes here

### ISSUE THREAD

**Issue by mobilekosmos** [Drjacky/MVVMTemplate#21]
Please provide a video showcasing how this template can be used. If you really want to use this as a template it should be easy to use another REST API by simply changing some data structures, layouts being used, etc., as this project is so massive (unbelieable how much work you put in it), it is difficult to find where to start and where to change something.

**Comment by Drjacky** [comment]
I'd suggest you read about Clean Architecture, Modularization and MVVM.
For example here: https://medium.com/proandroiddev/mvvm-with-clean-architecture-c2c021e05c89

For the UI, look at `presentation`.
Remember that I have used RxJava and Coroutine to show the usages.
So, the codebase contains both. Follow the one that suits you more. I tried to distinguish the Coroutine ones by adding ...`ByCoroutine` to the end of the names (class names, method names, etc).

The Use Template comes from Github itself: https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template
