### ISSUE TITLE
Could not clone: Drjacky/MVVMTemplate is not a template repository.

### ISSUE THREAD

**Issue by mage1k99** [Drjacky/MVVMTemplate#3]
Getting **Could not clone: Drjacky/MVVMTemplate is not a template repository** while cloning

**Comment by Drjacky** [comment]
@mage1k99 
How you do this?! I tried right now and it worked!
<img width="485" alt="Screen Shot 2020-06-25 at 12 37 10" src="https://user-images.githubusercontent.com/2296754/85704471-99f32600-b6e0-11ea-8a75-e8fe67b7f3fc.png">

**Comment by Drjacky** [comment]
Yes, Github [randomly](https://github.com/paularmstrong/monorepo-ts/issues/1) remove template option!
<img width="685" alt="Screen Shot 2020-06-25 at 12 39 39" src="https://user-images.githubusercontent.com/2296754/85704812-f1919180-b6e0-11ea-9bcd-177c2f972274.png">

Now, it's template; Again! 🤦🏻‍♂️
Sorry for any inconvenience. 🙏
