### ISSUE TITLE
Empty screen instead of no internet connection view

### ISSUE THREAD

**Issue by ZahraHeydari** [Drjacky/MVVMTemplate#56]
When choosing a coroutine button, no internet connection view is displayed. After the mobile device screen is off and then on, the view will be gone as you see in the attached video.

[![Watch the video](https://user-images.githubusercontent.com/15853759/218342107-676b1f98-7c9d-469c-adf6-d7eb645669f2.png)](https://user-images.githubusercontent.com/15853759/218341159-0cbbbd10-225c-432f-b7e1-5552c09cbd28.gif)

**Comment by Drjacky** [comment]
> as you see in the attached video.

I think the video has been removed or wrong image/video is attached!

**Comment by ZahraHeydari** [comment]
The image that I attached is clickable!

**Comment by Drjacky** [comment]
It is fixed by https://github.com/Drjacky/MVVMTemplate/commit/0673aca1c95ade37e2bf9194b8062454819f85ac. Thanks for reporting.
